# Site settings
title: Babbling with Lorinkoz
email: lorinkoz@gmail.com
description: >
  My journey in tech, faith and life.
  Best told via babbling.
baseurl: ""
url: "http://lorinkoz.github.io"
twitter_username: lorinkoz
github_username: lorinkoz

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
